/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
  'fullDescription' : IDL.Text,
  'price' : IDL.Float64,
});
export const BusinessInfo = IDL.Record({
  'businessName' : IDL.Text,
  'businessAddress' : IDL.Text,
  'aboutText' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'updateBusinessInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BusinessInfo],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
    'fullDescription' : IDL.Text,
    'price' : IDL.Float64,
  });
  const BusinessInfo = IDL.Record({
    'businessName' : IDL.Text,
    'businessAddress' : IDL.Text,
    'aboutText' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'updateBusinessInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BusinessInfo],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };