/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Text;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
  'imageUrl' : IDL.Text,
  'shortDescription' : IDL.Text,
  'fullDescription' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AIPromptEntry = IDL.Record({
  'transformationDescriptor' : IDL.Text,
  'promptText' : IDL.Text,
  'timestamp' : Time,
});
export const BusinessInfo = IDL.Record({
  'businessName' : IDL.Text,
  'businessAddress' : IDL.Text,
  'aboutText' : IDL.Text,
  'contactEmail' : IDL.Text,
  'contactPhone' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllAIPromptEntries' : IDL.Func([], [IDL.Vec(AIPromptEntry)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAIPromptEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBusinessInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [BusinessInfo],
      [],
    ),
  'updateProduct' : IDL.Func(
      [ProductId, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Text;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
    'imageUrl' : IDL.Text,
    'shortDescription' : IDL.Text,
    'fullDescription' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AIPromptEntry = IDL.Record({
    'transformationDescriptor' : IDL.Text,
    'promptText' : IDL.Text,
    'timestamp' : Time,
  });
  const BusinessInfo = IDL.Record({
    'businessName' : IDL.Text,
    'businessAddress' : IDL.Text,
    'aboutText' : IDL.Text,
    'contactEmail' : IDL.Text,
    'contactPhone' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllAIPromptEntries' : IDL.Func([], [IDL.Vec(AIPromptEntry)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAIPromptEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBusinessInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [BusinessInfo],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Text],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };