/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIPromptEntry {
  'transformationDescriptor' : string,
  'promptText' : string,
  'timestamp' : Time,
}
export interface BusinessInfo {
  'businessName' : string,
  'businessAddress' : string,
  'aboutText' : string,
  'contactEmail' : string,
  'contactPhone' : string,
}
export interface Product {
  'id' : ProductId,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'imageUrl' : string,
  'shortDescription' : string,
  'fullDescription' : string,
  'price' : number,
}
export type ProductId = string;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, number, string, string, string], Product>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllAIPromptEntries' : ActorMethod<[], Array<AIPromptEntry>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getBusinessInfo' : ActorMethod<[], BusinessInfo>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveAIPromptEntry' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBusinessInfo' : ActorMethod<
    [string, string, string, string, string],
    BusinessInfo
  >,
  'updateProduct' : ActorMethod<
    [ProductId, string, number, string, string, string],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];